### ISSUE TITLE
Benchmarking libraries against themselves

### ISSUE THREAD

**Issue by Themanwithoutaplan** [hakib/fast-excel-python#1]
You really don't need to look at Pandas and Tablib because they both depend on Openpyxl for the reading. You should start with that and the additional optimisation of `ws.iter_rows(values_only=True)` or just plain `ws.values` which avoids the creation of cell objects altogether. Getting integers is surprisingly costly in Python but the real bottleneck is the underlying parser. We use etree because it's the best way to handle reading and writing all the thousands of possible objects, but it's anything but fast. I've run some bottlenecks with other parsers and they're all much, much faster but the conversion to Python objects is slow. I might look at the underlying Rust XML parser; converting rows at once might be an acceptable compromise.
Iterating does, of course, allow streaming conversions and can be combined with multiprocessing for handling multiple sheets in the same workbook at once.

**Comment by hakib** [comment]
Thanks for the feedback.

> You really don't need to look at Pandas and Tablib because they both depend on Openpyxl for the reading. 

I included them because that's what people are using, and they have other advantages that might be worth considering so it was interesting to see if they add any significant overhead in addition to that of openpyxl. Also, pandas for example is going to get a python-calamine engine soon, so that's also interesting.

> You should start with that and the additional optimisation of ws.iter_rows(values_only=True) or just plain ws.values which avoids the creation of cell objects altogether. 

I tried what you suggested, using `iter_rows(values_only=True)` and `ws.values`. These are the three variations:

```python

import openpyxl
def iter_excel_openpyxl(file: IO[bytes]) -> Iterator[dict[str, object]]:
    workbook = openpyxl.load_workbook(file, read_only=True)
    rows = workbook.active.rows
    headers = [str(cell.value) for cell in next(rows)]
    for row in rows:
        yield dict(zip(headers, (cell.value for cell in row)))


import openpyxl
def iter_excel_openpyxl_iter_rows(file: IO[bytes]) -> Iterator[dict[str, object]]:
    workbook = openpyxl.load_workbook(file, read_only=True)
    rows = workbook.active.iter_rows(values_only=True)
    headers = next(rows)
    for row in rows:
        yield dict(zip(headers, row))



import openpyxl
def iter_excel_openpyxl_values(file: IO[bytes]) -> Iterator[dict[str, object]]:
    workbook = openpyxl.load_workbook(file, read_only=True)
    rows = workbook.active.values
    headers = next(rows)
    for row in rows:
        yield dict(zip(headers, row))
```

These were my results:

```
In [8]: %run benchmark.py

iter_excel_openpyxl
elapsed 20.62
{'number': 1, 'decimal': 1.1, 'date': datetime.datetime(2000, 1, 1, 0, 0), 'boolean': '=TRUE()', 'text': 'CONTROL ROW'}
🟢 "number"
🟢 "decimal"
🔴 "date" expected type "<class 'datetime.date'>" received type "<class 'datetime.datetime'>"
🟢 "boolean"
🟢 "text"

iter_excel_openpyxl_iter_rows
elapsed 19.08
{'number': 1, 'decimal': 1.1, 'date': datetime.datetime(2000, 1, 1, 0, 0), 'boolean': '=TRUE()', 'text': 'CONTROL ROW'}
🟢 "number"
🟢 "decimal"
🔴 "date" expected type "<class 'datetime.date'>" received type "<class 'datetime.datetime'>"
🟢 "boolean"
🟢 "text"

iter_excel_openpyxl_values
elapsed 19.37
{'number': 1, 'decimal': 1.1, 'date': datetime.datetime(2000, 1, 1, 0, 0), 'boolean': '=TRUE()', 'text': 'CONTROL ROW'}
🟢 "number"
🟢 "decimal"
🔴 "date" expected type "<class 'datetime.date'>" received type "<class 'datetime.datetime'>"
🟢 "boolean"
🟢 "text"
```

**I don't consider this a significant improvement**. AFAIK the most significant optimization for openpyxl is the one mentioned in the article - reading the sheet in readonly mode. Let me know if there is something else I should have done to further optimize openpyxl.

> We use etree because it's the best way to handle reading and writing all the thousands of possible objects, but it's anything but fast.

I actually considered including [xlsx2csv](https://github.com/dilshod/xlsx2csv/blob/master/xlsx2csv.py) int his benchmark (it's used by polars, among others). It uses Python `minidom` to read through the XML. In my benchmarks it came out ~36s, slowest than pandas even. Since it's converting to CSV and it's not providing any significant perf benefit I ended up leaving it out of the benchmark and the article.

**Comment by Themanwithoutaplan** [comment]
If you included Pandas and Tablib for the reasons you did, you still should reorder the article. The overhead is basically the reordering the data structures from rows to columns and possibly data type casting. Dates are **always** datetimes because the only sane serialisation uses the iso-format. 

`ws.values` is really just sugar for the `values_only=True` option. Read-only is really a memory optimisation with improvements heavily dependent on what else is in the workbook: Pivot tables and external links can really slow things down.

`values_only=True` varies across Python versions. Look at the code behind the benchmarks (https://openpyxl.readthedocs.io/en/stable/performance.html) for this, but it also says a lot about the optimisations that went into Python's slots implementation: these are incredibly fast objects. Optimisations in the language have brought more performance gains than anything I can do in the code, but you can squeeze a bit more out of it using a naive Cython conversion. A native int_or_float call would also be noticeable because it's a function that gets called for **every** number.

Between languages you're essentially comparing XML parsers. For Python xml.etree is the fastest even if it's also the most flexible but it's also a real memory hog. Last year I looked for alternative parsers and found a very promising C++ one with Python bindings, but performance goes down the toilet as soon as you start accessing the variables. You might want do a follow-up benchmark. The other great thing would be anything that can read contents from zip files in parallel.

Alternative backends for the simple conversion of tabular data, for which Excel is routinely abused, are more than welcome!

**Comment by hakib** [comment]
The oenpyxl benchmarks seem to focus on writing and not reading. I'm sure further optimization can be made but they all seem difficult and probably more than what the average user would be willing to go through to read an Excel file ;)

I think we got the most out of openpyxl at this point so I'm going to close this for now.
